# The steps to build and deploy
# 1. check out code
# 2. login to aws ecr
# 3. build and push image to aws ecr
name: Build and Push Docker Image to AWS ECR
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Push Docker Image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      # Checkout code from repository
      - name: Checkout Code
        uses: actions/checkout@v3
        # Log in to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'
          cache: 'maven'
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
          restore-keys:
            ${{runner.os}}-m2
      - name: Build, Tag and Push to ECR
        env:
          ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG: ${{github.sha}}
        run: |
          echo "Generate Docker tag: $IMAGE_TAG"
          docker build -t $ECR_REPOSITORY_URI:$IMAGE_TAG -t ECR_REPOSITORY_URI:latest .
          docker push -a ECR_REPOSITORY_URI



